project:
  type: book
  output-dir: output
book:
  title: "Tips and Tricks about R and Quarto"
  author: "Minh-Anh Huynh"
  date: "21/09/2023"
  chapters:
    - index.qmd
    - chapters/thesis/thesis.qmd
    - chapters/ggplot2/ggplot2.qmd
    - chapters/references.qmd

bibliography: chapters/references.bib

format:
  html:
    theme: solar
  pdf:
    documentclass: scrreprt

execute:
  freeze: auto
